export const ADDED ='todo/added'
export const TOGGLED ='todo/toggled'
export const COLORSELECTED ='todo/colorselected'
export const DELETED ='todo/deleted'
export const ALLCOMPLETE ='todo/allcomplete'
export const CLEARCOMPLETED ='todo/clearcomplted'